### ISSUE TITLE
Support iOS 9.0

### ISSUE THREAD

**Issue by zigdanis** [glassonion1/RxStoreKit#1]
Hi! Thanks for the Rx wrapper around StoreKit👍
It looks like you don't use iOS 10 specific APIs. Can you lower minimum iOS version to 9.0?

**Comment by glassonion1** [comment]
Thanks for your comment.
Version 1.0.1 supported iOS9.
Please try pod command 'pod update'.

**Comment by zigdanis** [comment]
Great!
