### ISSUE TITLE
Finish transaction after it was validated on own server

### ISSUE THREAD

**Issue by zigdanis** [glassonion1/RxStoreKit#2]
Is it possible to defer finishing transactions until they were verified on our own server?
I'm using consumable products and user can possibly fail to upload purchase receipt to our own server for validating it. So next time this purchase won't be available to proceed, because it was already marked as finished.

**Comment by glassonion1** [comment]
Deleted 'finish transaction' code on this pull request.
https://github.com/glassonion1/RxStoreKit/pull/3
